<AnotherButton>:
    id: root.id
    padding: 5
    orientation: 'vertical'
    size_hint: 1, None
    #TODO: Вернуться к этому решению с функцией коллбек
    #on_release: root.events_callback()
    canvas:
        Color:
            rgba: root.rgba_color
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        id: head
        font_size: '25'
        text: root.head
    Label:
        id: body
        font_size: '18'
        text: root.body